// Generated by tools/emoji_roles.py from tools/emoji_roles.json. Do not edit.
#pragma once

namespace EmojicodeLanguageServer::EmojiRoles {

/// keyword emoji, without U+FE0F.
constexpr const char32_t *kKeyword = U"🏁📦📜🔗🙅🤷♻↪";
/// modifier emoji, without U+FE0F.
constexpr const char32_t *kModifier = U"🌍🔏✒🥯⚠🔑☣🖍🔓🔒🔐📻🍼";
/// operator emoji, without U+FE0F.
constexpr const char32_t *kOperator = U"➕➖➗✖👐🤝⭕💢❌👈👉🚮🙌😜◀▶";
/// typeOperator emoji, without U+FE0F.
constexpr const char32_t *kTypeOperator = U"🍺🔺🔲⚖🏮🍬✴⬛🚧🍱";
/// builtinType emoji, without U+FE0F.
constexpr const char32_t *kBuiltinType = U"◼⚪🔵⚫";

}  // namespace EmojicodeLanguageServer::EmojiRoles
