#!/usr/bin/env python3
"""Generates EmojiNames.hpp, the Unicode names of the emoji the lexer accepts, for completing emoji by name.

The emoji are read from isEmoji() in Compiler/Lex/EmojiTokenization.cpp. Run this after changing that function.
"""
import os
import re
import unicodedata

here = os.path.dirname(os.path.abspath(__file__))
source = open(os.path.join(here, "..", "Compiler", "Lex", "EmojiTokenization.cpp"), encoding="utf-8").read()
body = source[source.index("bool isEmoji("):]
body = body[:body.index("\n}\n")]

code_points = set()
for low, high in re.findall(r"\(0x([0-9A-Fa-f]+) <= ch && ch <= 0x([0-9A-Fa-f]+)\)", body):
    code_points.update(range(int(low, 16), int(high, 16) + 1))
for single in re.findall(r"ch == 0x([0-9A-Fa-f]+)", body):
    code_points.add(int(single, 16))

entries = []
for c in sorted(code_points):
    if 0x1F1E6 <= c <= 0x1F1FF or 0x1F3FB <= c <= 0x1F3FF:
        continue  # Regional indicators and skin tones are only parts of emoji.
    name = unicodedata.name(chr(c), "")
    if name:
        entries.append((c, name.lower()))

with open(os.path.join(here, "EmojiNames.hpp"), "w", encoding="utf-8") as f:
    f.write("""//
//  EmojiNames.hpp
//  EmojicodeLanguageServer
//
//  Generated by generate_emoji_names.py from the Unicode {0} names. Do not edit.
//

#ifndef EmojiNames_hpp
#define EmojiNames_hpp

namespace EmojicodeLanguageServer {{

struct EmojiName {{
    char32_t emoji;
    const char *name;
}};

const EmojiName kEmojiNames[] = {{
""".format(unicodedata.unidata_version))
    for c, name in entries:
        f.write('    {{0x{0:X}, "{1}"}},\n'.format(c, name))
    f.write("""};

}  // namespace EmojicodeLanguageServer

#endif /* EmojiNames_hpp */
""")
print(len(entries), "emoji")
