// Generated by emojicodec. Calls C functions that take or return structs by value.

#include <stdint.h>

struct ejc_struct_0 {
    int32_t f0;
    int32_t f1;
};

extern struct ejc_struct_0 ffiPackageAdd(struct ejc_struct_0, struct ejc_struct_0);

void __ejc_tramp_17ffiPackagePackage_ffiPackageAdd(struct ejc_struct_0 *a0, struct ejc_struct_0 *a1, struct ejc_struct_0 *result) {
    *result = ffiPackageAdd(*a0, *a1);
}

