// Generated by tools/emoji_roles.py from tools/emoji_roles.json. Do not edit.

export const keywordEmoji: readonly string[] = ['🏁', '📦', '📜', '🔗', '🙅', '🤷', '♻', '↪'];
export const modifierEmoji: readonly string[] = ['🌍', '🔏', '✒', '🥯', '⚠', '🔑', '☣', '🖍', '🔓', '🔒', '🔐', '📻', '🍼'];
export const operatorEmoji: readonly string[] = ['➕', '➖', '➗', '✖', '👐', '🤝', '⭕', '💢', '❌', '👈', '👉', '🚮', '🙌', '😜', '◀', '▶'];
export const typeOperatorEmoji: readonly string[] = ['🍺', '🔺', '🔲', '⚖', '🏮', '🍬', '✴', '⬛', '🚧', '🍱'];
export const builtinTypeEmoji: readonly string[] = ['◼', '⚪', '🔵', '⚫'];
