#!/usr/bin/env python3
"""Generates the emoji tables that the language server and the editors share from tools/emoji_roles.json.

Writes LanguageServer/EmojiRoles.hpp, editors/vscode/src/emojiRoles.ts and the marked block in
editors/tree-sitter-emojicode/queries/highlights.scm. editors/vscode/syntaxes/generate.py reads the JSON itself.
With --check nothing is written and the exit status says whether the generated files are up to date.
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.join(HERE, '..')
ROLES_PATH = os.path.join(HERE, 'emoji_roles.json')
CPP_PATH = os.path.join(ROOT, 'LanguageServer', 'EmojiRoles.hpp')
TS_PATH = os.path.join(ROOT, 'editors', 'vscode', 'src', 'emojiRoles.ts')
SCM_PATH = os.path.join(ROOT, 'editors', 'tree-sitter-emojicode', 'queries', 'highlights.scm')
SCM_BEGIN = '; BEGIN generated by tools/emoji_roles.py\n'
SCM_END = '; END generated\n'
NOTE = 'Generated by tools/emoji_roles.py from tools/emoji_roles.json. Do not edit.'


def load_roles():
    with open(ROLES_PATH, encoding='utf-8') as f:
        roles = json.load(f)
    roles.pop('_comment', None)
    return {role: list(emoji) for role, emoji in roles.items()}


def cpp(roles):
    lines = ['// ' + NOTE, '#pragma once', '', 'namespace EmojicodeLanguageServer::EmojiRoles {', '']
    for role, emoji in roles.items():
        lines.append('/// {} emoji, without U+FE0F.'.format(role))
        lines.append('constexpr const char32_t *k{}{} = U"{}";'.format(role[0].upper(), role[1:], ''.join(emoji)))
    lines += ['', '}  // namespace EmojicodeLanguageServer::EmojiRoles', '']
    return '\n'.join(lines)


def typescript(roles):
    lines = ['// ' + NOTE, '']
    for role, emoji in roles.items():
        lines.append('export const {}Emoji: readonly string[] = [{}];'.format(
            role, ', '.join("'{}'".format(e) for e in emoji)))
    return '\n'.join(lines) + '\n'


def quoted(emoji):
    return ' '.join('"{}"'.format(e) for e in emoji)


def highlights(roles, current):
    block = SCM_BEGIN + '["{}"] @keyword.modifier\n'.format(''.join(roles['modifier'])).replace('"' + ''.join(
        roles['modifier']) + '"', quoted(roles['modifier'])) + SCM_END
    begin, end = current.index(SCM_BEGIN), current.index(SCM_END) + len(SCM_END)
    return current[:begin] + block + current[end:]


def outputs():
    roles = load_roles()
    with open(SCM_PATH, encoding='utf-8') as f:
        current = f.read()
    return {CPP_PATH: cpp(roles), TS_PATH: typescript(roles), SCM_PATH: highlights(roles, current)}


def main():
    stale = []
    for path, text in outputs().items():
        try:
            with open(path, encoding='utf-8') as f:
                same = f.read() == text
        except FileNotFoundError:
            same = False
        if not same:
            stale.append(os.path.relpath(path, ROOT))
            if '--check' not in sys.argv:
                with open(path, 'w', encoding='utf-8') as f:
                    f.write(text)
    if '--check' in sys.argv and stale:
        print('Out of date, run tools/emoji_roles.py: ' + ', '.join(stale))
        return 1
    return 0


if __name__ == '__main__':
    sys.exit(main())
