// Generated by emojicodec. Calls C functions that take or return structs by value.

#include <stdint.h>

struct ejc_struct_0 {
    int32_t f0;
    int32_t f1;
};

struct ejc_struct_1 {
    double f0;
    double f1;
};

struct ejc_struct_2 {
    int64_t f0;
    int64_t f1;
    int64_t f2;
    float f3;
};

struct ejc_struct_3 {
    struct ejc_struct_0 f0;
    struct ejc_struct_0 f1;
};

struct ejc_struct_4 {
    int8_t f0;
    int16_t f1;
};

struct ejc_struct_5 {
    int32_t f0;
    int32_t f1;
};

struct ejc_struct_6 {
    int64_t f0;
    int64_t f1;
};

extern struct ejc_struct_0 ffiPointAdd(struct ejc_struct_0, struct ejc_struct_0);

void __ejc_tramp_1__ffiPointAdd(struct ejc_struct_0 *a0, struct ejc_struct_0 *a1, struct ejc_struct_0 *result) {
    *result = ffiPointAdd(*a0, *a1);
}

extern struct ejc_struct_1 ffiComplexMultiply(struct ejc_struct_1, struct ejc_struct_1);

void __ejc_tramp_1__ffiComplexMultiply(struct ejc_struct_1 *a0, struct ejc_struct_1 *a1, struct ejc_struct_1 *result) {
    *result = ffiComplexMultiply(*a0, *a1);
}

extern struct ejc_struct_2 ffiBigMake(int64_t, int64_t, int64_t, float);

void __ejc_tramp_1__ffiBigMake(int64_t a0, int64_t a1, int64_t a2, float a3, struct ejc_struct_2 *result) {
    *result = ffiBigMake(a0, a1, a2, a3);
}

extern double ffiBigSum(struct ejc_struct_2);

double __ejc_tramp_1__ffiBigSum(struct ejc_struct_2 *a0) {
    return ffiBigSum(*a0);
}

extern int32_t ffiRectArea(struct ejc_struct_3);

int32_t __ejc_tramp_1__ffiRectArea(struct ejc_struct_3 *a0) {
    return ffiRectArea(*a0);
}

extern struct ejc_struct_4 ffiSmallNext(struct ejc_struct_4);

void __ejc_tramp_1__ffiSmallNext(struct ejc_struct_4 *a0, struct ejc_struct_4 *result) {
    *result = ffiSmallNext(*a0);
}

extern struct ejc_struct_5 div(int32_t, int32_t);

void __ejc_tramp_1__div(int32_t a0, int32_t a1, struct ejc_struct_5 *result) {
    *result = div(a0, a1);
}

extern struct ejc_struct_6 ldiv(int64_t, int64_t);

void __ejc_tramp_1__ldiv(int64_t a0, int64_t a1, struct ejc_struct_6 *result) {
    *result = ldiv(a0, a1);
}

